camera: hik

odom2camera:
  xyz: "\"0.14386 0.0685  -0.01\""
  rpy: "\"0.0  0.0  0.0\""

detector_log_level: INFO
tracker_log_level: INFO
serial_log_level: INFO
# auto_record_log_level: INFO
