image_width: 1280
image_height: 960
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [2419.51921,    0.     ,  709.18938,
            0.     , 2415.62379,  555.38108,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.040200, 0.258560, -0.001912, 0.002829, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2416.34229,    0.     ,  710.18139,    0.     ,
            0.     , 2413.89429,  553.99412,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]